---
# tasks file for wordpress-docker

- name: cleanup docker service directory
  file: path={{ wordpress.app.path }}
        state=absent
  notify:
    - "cleanup wordpress docker"
  tags:
    - cleanup

- name: create docker service directory
  file: path={{ wordpress.app.path }}
        state=directory
        mode=0755
        owner=root group=root

- name: create docker nginx config directory
  file: path={{ wordpress.app.path }}/nginx
        state=directory
        mode=0755
        owner=root group=root

- name: deploy docker compose file
  template: src=docker-compose.yml.j2
            dest={{ wordpress.app.path }}/docker-compose.yml
            owner=root group=root
  notify:
    - "restart wordpress docker"

- name: deploy docker nginx site config
  template: src=nginx-default.conf.j2
            dest={{ wordpress.app.path }}/nginx/default.conf
            owner=root group=root
  notify:
    - "restart wordpress docker"
