---
# handlers file for wordpress-docker
- name: start wordpress docker
  docker_service:
    project_name: "{{ wordpress.app.name }}"
    project_src: "{{ wordpress.app.path }}"
    recreate: always
  listen: "restart wordpress docker"

- name: check wordpress docker
  assert:
    that:
      - "db.wordpress_db_1.state.running"
      - "web.wordpress_web_1.state.running"
  listen: "restart wordpress docker"
